### ISSUE TITLE
kling 1.5 support

### ISSUE THREAD

**Issue by lschaupp** [yihong0618/klingCreator#19]

**Comment by yihong0618** [comment]
will take a look these days

**Comment by fdsiusdbgittewhif** [comment]
This would be a great addition

**Comment by yihong0618** [comment]
what about make all the model to 1.5?
or set it as an option?

**Comment by yihong0618** [comment]
Done please check Readme for more info

**Comment by lschaupp** [comment]
python -m kling --type video  --prompt '一只奔跑的狗' --model_name 1.5

is not working. I think you forgot the high quality flag which is also required.

**Comment by yihong0618** [comment]
@lschaupp thanks fixed
